# SPDX-FileCopyrightText: 2026 Free Sales Forecast contributors
# SPDX-License-Identifier: MIT
apiVersion: v1
kind: Secret
metadata:
  name: free-sales-forecast-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://forecast:forecast@free-sales-forecast-postgres:5432/forecast
  S3_ACCESS_KEY: minio
  S3_SECRET_KEY: minio123
